//
//  Constant.swift
//  MySunless
//
//  Created by iMac on 06/10/21.
//

import Foundation

let BASE_URL = "http://api.mysunless.com/api/"
let LOGIN = "login"
let SEND_CODE = "sendotp"
let VERIFY_CODE = "verifyotp"
let STORE_USER = "storeuser"
let SHOW_PACKAGE = "showpackage"
let SET_USERNAME = "setusername"
let FORGOT_PASSWORD = "forgotpassword"
let USER_PROFILE = "userprofile"
let USER_AVATAR = "useravtar"
let CHANGE_PASSWORD = "changepassword"
let UPDATE_PROFILE = "updateprofile"
let SUBSCRIPTIONS_LIST = "usersubscriptions"
let SAVE_SIGNATURE = "savesignature"
let SAVE_GOALS = "updategoal"
let LOGOUT = "logout"
let ALL_CLIENTS = "allclients"
let SAVE_CLIENT = "saveclient"
let DELETE_CLIENTID = "DeleteClientId"
let SHOW_EMPLOYEE = "showemployee"
let SAVE_EMPLOYEE = "employeestore"
let SHOW_COMPANY = "company/showcompany"
let UPDATE_COMPANY = "company/updatecompany"
let DELETE_EMPLOYEE = "deleteemployee"
let UPDATE_EMPLOYEE = "updateemployee"
let SET_CUSTOM_DATETIME = "SetCutomDateTime"
let DELETE_BLOCKTIME = "DeleteBlockTime"
let SET_TIME = "SetTime"
let ADD_TEMPLATE = "AddTemplate"
let EDIT_TEMPLATE = "EditTemplate"
let CHANGE_TEMPLATE_STATUS = "ChangeTemplateStatus"
let VIEW_TEMPLATE = "ViewTemplate"
let DELETE_TEMPLATE = "DeleteTemplate"
let ADD_PACKAGE = "AddPackage"
let EDIT_PACKAGE = "EditPackage"
let DELETE_PACKAGE = "deletePackage"
let SELECT_SERVICE = "SelectService"
let CHOOSE_PACKAGE = "ChoosePackage"
let PACKAGE_STATUS = "PackageStatus"
let SHOW_ACTIVE_MEMBER = "ShowActiveMember"
let UPCOMING_RENEWALS = "UpcomingRenewals"
let COMPLETED_AND_EXPIRED = "CompletedAndExpired"
let DELETE_ACTIVE_PACKAGE = "deleteActivePackage"
let SELECT_SERVICE_APPOINTMENT = "AppointmentService"
let CHOOSE_CUSTOMER = "ChooseCustomer"
let SHOW_CLIENT_PRIVATE_NOTE = "ShowClientPrivateNote"
let GET_SERVICE_PROVIDER = "GetProvider"
let FILTER_CHOOSE_USER = "filterListUser"
let FILTER_CHOOSE_CUSTOMER = "filterListCustomer"
let SHOW_EVENT = "ShowEvent"
let UPDATE_EVENT_STATUS = "UpdateEventStatus?id&status"
let DELETE_EVENT = "DeleteEvent"
let AVAILABLE_TIMESLOT = "GetTime"
let SHOW_CLIENT_ALLNOTES = "ShowClientSAllNotes"
let ADD_NOTE = "AddNote"
let DELETE_NOTE = "DeleteClientNote"
let SHOW_COMPLETED_ORDER = "ShowCompletedOrder"
let SHOW_PENDING_ORDER = "ShowPendingOrder"
let DELETE_ORDER = "DeleteOrder"
let CHANGE_PAYMENT_STATUS = "ChangePaymentStatus"
let SHOW_PERFORMANCE = "ShowPerformance"
let SHOW_LOGINLOG = "ShowLoginInfo"
let SHOW_LISTOFSERVICE = "ShowListOfService"
let DELETE_SERVICE = "DeleteService"
let ADD_NEW_SERVICE = "AddNewService"
let SHOW_BANNER_IMAGE_LIST = "ShowBannerImageList"
let SHOW_GALLARY_IMAGE_LIST = "ShowGallaryImageList"
let DELETE_BANNER_IMAGE = "DeleteBannerImage"
let DELETE_GALLARY_IMAGE = "DeleteGallaryImage"
let UPDATE_GALLARYIMAGE_LIST = "UpdateGallaryImageList?updateid="
let ADD_BANNER_IMAGE = "AddBannerImage"
let ADD_GALLARY_IMAGE = "AddGallaryImage"
let SHOW_SERVICE_LIST = "ShowServiceList"
let RESTORE_SERVICE = "RestoreService"
let SHOW_EVENT_LIST = "ShowEventList"
let RESTORE_EVENT = "RestoreEvent"
let SHOW_CLIENT = "ShowClient"
let RESTORE_CLIENT = "RestoreClient"
let DELETE_CLIENT = "DeleteClient"
let SHOW_PRODUCT_CATEGORY = "ShowProductCategory"
let RESTORE_PRODUCT_CATEGORY = "RestoreProductcategory"
let SHOW_MEMBERSHIP_PACKAGE = "ShowMembershipPackage"
let RESTORE_MEMBERSHIP_PACKAGE = "RestoreMembershipPackage"
let SHOW_PRODUCT_LIST = "ShowProductList"
let RESTORE_PRODUCT = "RestoreProduct"
let VIEW_APPOINTMENT_USERINFO = "ViewAppointmentUserInfo"
let CHANGE_APPOINTMENT_STATUS = "ChangeAppointmentStatus"
let APP_OVERVIEW = "AppOverview"
let DELETE_APPOINTMENT_INFO = "DeleteAppointmentInfo"
let GET_CUSTOMER_LIST = "GetCustomerList"
let VIEW_SALES_USERINFO = "ViewSalesUserInfo"
let SALES_OVERVIEW = "SalesOverview"
let SINGLE_CLIENT = "singleclient"
let LAST_SERVICE_DATE = "LastServiceDate"
let GIFT_CARD_BALANCE = "GiftCardBalance"
let SHOW_DOCUMENT = "Showdocument"
let UPLOAD_DOCUMENT = "UploadDocument"
let DELETE_DOCUMENT = "DeleteDocument"
let VIEW_NOTE = "ViewNote"
let ORDER_HISTORY = "OrderHistory"
let CONTACT_CLIENT = "CommunicationHistory"
let PACKAGE_HISTORY = "PackageHistory"
let DAILY = "Daily"
let BOOK_APPOINTMENT = "BookAppointment"
let MEMBER_PACKAGE = "MemberPackage"
let ORDER_SERVICE = "OrderService"
let VIEW_PRODUCT = "ViewProduct"
let ORDER_PRODUCT = "OrderProduct"
let VIEW_PACKAGE = "ViewPackage"
let ORDER_PACKAGE = "OrderPackage"
let ORDER_GIFT = "OrderGift"
let GIFT_CARD_BAL = "GiftCardBal"
let ORDER_BOOK = "OrderBook"
let VIEW_INVOICE = "OrderInvoiceModal"
let CASH_PAYMENT = "CashPayment"
let CHEQUE_PAYMENT = "CheqPayment"
let ORDER_INVOICE_MAIL = "OrderInvoiceMail"
let UPDATE_INVOICE_NOTES = "updateInvoiceNotes"
let PRODUCT_REPORT = "viewProductSaleReport"
let CATEGORY_REPORT = "viewCategoryReport"
let PAYMENT_LIST = "PaymentList"
let TOP_SELLING_PRODUCTS = "topSellingProducts"
let RECENT_TRANSACTION = "recentTransaction"
let DISPLAY_INFO_FIRST_ROW = "displayInfoFirstRow"
let PRODUCT_SALES_REPORT = "productSalesReport"
let REVENUE_REPORT = "revenueReport"
let SHOW_PRODUCTS = "showproducts"
let UPDATE_PROD_STATUS = "UpdateProdStatus"
let ADD_PRODUCT_CATEGORY = "AddProdCat"
let SHOW_PRODUCT_CATEGORY_INVENTORY = "ShowProductCategoryinventory"
let SHOW_PRODUCT_BRAND = "ShowProductBrand"
let ADD_PRODUCT = "ProductBarcode"
let ADD_BARCODE = "AddBarcode"
let LIST_OF_PROD_CAT = "listofprodcat"
let DELETE_PRODUCT_CATEGORY = "DeleteProductCategory"
let GET_PROD_BY_BARCODE = "GetProdByBarcode"
let ADD_PRODUCT_BRAND = "addProductBrand"
let DELETE_PRODUCT_BRAND = "deleteProductBrand"
let DELETE_PRODUCT = "DeleteProduct"
let LIST_APPOINTMENT = "ListAppointment"
let REQUESTED_EVENT_LIST = "selectNotAcceptAppointment"
let ACCEPT_APPOINTMENT = "AcceptAppointment"
let NOT_ACCEPT_APPOINTMENT = "NotAcceptEvent"
let SEND_SMS_TO_CLIENT = "SendSmsToClient"
let SEND_MAIL = "SendMailButton"
let SHOW_REMINDER_DATA = "showReminderData"
let EDIT_REMINDER = "EditReminder"
let SALE_PROFIT_GRAPH = "SaleProfitGraph"
let ADD_SQUARE = "AddSquare"
let SHOW_SQUARE = "ShowSquare"
let DISABLE_SQUARE = "DesableSquare"
let ADD_STRIPE = "Addstripe"
let SHOW_STRIPE_DATA = "ShowStripeData"
let DISABLE_STRIPE = "DesableStripe"
let DELETE_FROM_LIST = "DeleteFromList"
let Update_Event_Status = "UpdateEventStatus"
let DOWNLOAD_PDF = "download_pdf"
let SALES_GRAPH = "OrderChart"
let EVENTS_GRAPH = "EventChart"
let SHOW_EMPLOYEE_TIME = "ShowEmployeeTime"
//ApplePay
let IN_APP_PURCHASE = "ApplePay"
let SUBSCRIBER_LIST = "subscriberList"
let SUBSCRIBER_STATUS = "subscriberStatus"
let SUBSCRIBER_ADMINFILTER = "getuserforfilter"
let ADD_CATEGORY = "AddCategory"
let SHOWALL_TODO_CATEGORY = "ShowAllTodoCategory"
let SHOWALL_TASK = "ShowAllTask"
let DELETE_CATEGORY = "DeleteCategory"
let ADD_TASK = "AddTask"
let DELETE_TASK = "DeleteTask"
let CHANGE_CATEGORY = "ChangeCategory"
let SHOW_ARCHIVE_TASK = "ShowArchiveTask"
let EXPORT_CLIENT_SHEET = "exportClientSheet"
let IMPORT_CLIENT_SHEET = "importClientSheet"
let VIEW_TASK_DETAIL = "ViewTaskDetail"
let UPDATE_PREVIEW_DATA = "updatepreview"
let POST_COMMENT = "AddOrUpdateComment"
let DELETE_COMMENT = "DeleteChat"


let stateList = ["Select a State","Alabama","Alaska","Arizona","Arkansas","California","Colorado","Connecticut","Delaware","Florida","Georgia","Hawai","Idaho","Illinois","Indiana","Lowa","Kansas","Kentucky","Louisiana","Maine","Maryland","Massachusetts","Michigan","Minnesota","Mississippi","Missouri","Montana","Nebraska","Nevada","New Hampshire","New Jersey","New Mexico","New York,","North Carolina","North Dakota","Ohio","Oklahoma","Oregon","Pennsylvania","Rhode Island","South Carolina","South Dakota","Tennessee","Texas","Utah","Vermont","Virginia","Washington","West Virginia","Wisconsin","Wyoming"]
let serviceDuration = ["Select Service Duration","0 Min","15 Min","30 Min","1 h","2 h","3 h","4 h","5 h","6 h","7 h","8 h","9 h","10 h","11 h","12 h"]
let companyTypeList = ["Select Company Type","MOBILE_TANNING_BUSINESS","SALON_BASED_BUSINESS"]
let clientGoalList = ["Select Client Goal","10","20","50","100","250","500","1000","5000","10000","50000"]
let salesGoalList = ["Select Sales Goal","5000","10000","25000","50000","100000","250000","500000","1000000"]
let filterDays = ["Today","Yesterday","Last 7 days","Last 30 Days","This Month","Last Month","Year to Date","Custom Range"]
let monthArr = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"]
//let arrProductIds = ["23","24","25","19","21"]
let arrProductIds = ["24","25","19","21"]
let arrEventStatus = ["completed","pending","confirmed","canceled","pending-payment","in-progress"]


//enum ProductType: String {
//   // case weekly = "com.example.app.weekly"
//    case monthly = "23"
//   // case yearly = "com.example.app.yearly"
//
//    static var all: [ProductType] {
//      //  return [.weekly, .monthly, .yearly]
//        return [.monthly]
//    }
//}
